-- SQLite
INSERT INTO departments (id, name, office_id, department_head_id) VALUES
(42,'Human Resource Development Division','1','127'),
(43,'General Services Division','1','137'),
(44,'Records Division','1','159'),
(45,'Accounting Division','2','163'),
(46,'Budget Division','2','168'),
(47,'Enforcement Division','3','244'),
(48,'Legal Assistance Division','3','244'),
(49,'Management Division','4','179'),
(50,'Planning,  Monitoring and Evaluation Division','4','186'),
(51,'Information and Communications Technology Division','5','118'),
(52,'Public Affairs Division','6','358'),
(53,'Office of the Executive Commissioner','8',NULL),
(54,'Office of Commissioner FJE','26',NULL),
(55,'Office of Commissioner SEY','27',NULL),
(56,'Office of Commissioner JCM','28',NULL),
(57,'Office of Commissioner MPC','29',NULL),
(58,'Office of the Director - AS','1',NULL),
(59,'Office of the Director - FS','2',NULL),
(60,'Office of the Director - PMS','4',NULL),
(61,'Office of the Director - LS','3',NULL),
(62,'Office of the Executive Clerk','7','24'),
(63,'Commission on Audit','25',NULL),
(66,'Office of the Regional Adjudicator - NCR','9',NULL),
(67,'Office of the Regional Adjudicator  - CAR','10',NULL),
(68,'Office of the Regional Adjudicator - I','11',NULL),
(69,'Office of the Regional Adjudicator - II','12',NULL),
(70,'Office of the Regional Adjudicator - III','13',NULL),
(71,'Office of the Regional Adjudicator - IV A','14',NULL),
(72,'Office of the Regional Adjudicator - IV B','15',NULL),
(73,'Office of the Regional Adjudicator - V','16',NULL),
(74,'Office of the Regional Adjudicator - VI','17',NULL),
(75,'Office of the Regional Adjudicator - VII','18',NULL),
(76,'Office of the Regional Adjudicator - VIII','19',NULL),
(77,'Office of the Regional Adjudicator - IX','20',NULL),
(78,'Office of the Regional Adjudicator - X','21',NULL),
(79,'Office of the Regional Adjudicator - XI','22',NULL),
(80,'Office of the Regional Adjudicator - XII','23',NULL),
(81,'Office of the Regional Adjudicator - XIII','24',NULL),
(82,'Administrative and Finance Division - NCR','9','318'),
(83,'Administrative and Finance Division - CAR','10',NULL),
(84,'Administrative and Finance Division - I','11',NULL),
(85,'Administrative and Finance Division - II','12',NULL),
(86,'Administrative and Finance Division - III','13',NULL),
(87,'Administrative and Finance Division - IV A','14',NULL),
(88,'Administrative and Finance Division - IV B','15','325'),
(89,'Administrative and Finance Division - V','16',NULL),
(90,'Administrative and Finance Division - VI','17',NULL),
(91,'Administrative and Finance Division - VII','18',NULL),
(92,'Administrative and Finance Division - VIII','19',NULL),
(93,'Administrative and Finance Division - IX','20',NULL),
(94,'Administrative and Finance Division - X','21',NULL),
(95,'Administrative and Finance Division - XI','22',NULL),
(96,'Administrative and Finance Division - XII','23',NULL),
(97,'Administrative and Finance Division - XIII','24',NULL),
(98,'Legal Division - NCR','9','38'),
(99,'Legal Division - CAR','10',NULL),
(100,'Legal Division - I','11',NULL),
(101,'Legal Division - II','12',NULL),
(102,'Legal Division - III','13',NULL),
(103,'Legal Division - IV A','14',NULL),
(104,'Legal Division - IV B','15','136'),
(105,'Legal Division - V','16',NULL),
(106,'Legal Division - VI','17',NULL),
(107,'Legal Division - VII','18',NULL),
(108,'Legal Division - VIII','19',NULL),
(109,'Legal Division - IX','20',NULL),
(110,'Legal Division - X','21',NULL),
(111,'Legal Division - XI','22',NULL),
(112,'Legal Division - XII','23',NULL),
(113,'Legal Division - XIII','24',NULL)
;