-- SQLite
INSERT INTO positions (id, name, status) VALUES
(1,'Director IV','A'),
(2,'Attorney VI','A'),
(3,'Attorney V','A'),
(4,'Development Manager Officer V','A'),
(5,'Security Officer V','A'),
(6,'Administrative Assistant II','A'),
(8,'Housing and Homesite Regulation Officer II','A'),
(9,'Administrative Officer V','A'),
(10,'Deputy Executive Director IV','A'),
(11,'Information Technology Officer III','A'),
(12,'Information Technology Officer II','A'),
(13,'Information Technology Officer I','A'),
(14,'Information Systems Analyst III','A'),
(15,'Information Systems Analyst I','A'),
(16,'Computer Maintenance Technologist II','A'),
(17,'Public Relations Officer V','A'),
(18,'Housing and Homesite Regulation Officer I','A'),
(19,'Housing and Homesite Regulation Officer III','A'),
(20,'Housing and Homesite Regulation Officer IV','A'),
(21,'Housing and Homesite Regulation Officer V','A'),
(22,'Attorney IV','A'),
(23,'Administrative Aide IV','A'),
(24,'Executive Commisioner ','A'),
(25,'Commisioner','A'),
(26,'Executive Assistant IV','A'),
(27,'Executive Assistant III','A'),
(28,'Executive Assistant II','A'),
(29,'Senior Administative Assistant III','A'),
(30,'Administrative Assistant V','A'),
(31,'Administrative Assistant III','A'),
(32,'Planning Officer IV','A'),
(33,'Planning Officer III','A'),
(34,'Planning Officer II','A'),
(35,'Planning Officer I','A'),
(36,'Legal Assistant III','A'),
(37,'Legal Assistant II','A'),
(38,'Sheriff II','A'),
(39,'Chief Administrative Officer','A'),
(40,'Supervising Administrative Officer','A'),
(41,'Administrative Officer IV','A'),
(42,'Administrative Officer III','A'),
(43,'Administrative Officer II','A'),
(44,'Administrative Officer I','A'),
(45,'Administrative Assistant I','A'),
(46,'Accountant IV','A'),
(47,'Accountant III','A'),
(48,'Public Relations Officer IV','A'),
(49,'Public Relations Officer III','A'),
(50,'Public Relations Officer II','A'),
(51,'Public Relations Officer I','A'),
(52,'Administrative Aide VI','A'),
(53,'Director III (Chief Regional Adjudicator)','A'),
(54,'Director II (Assistant Regional Adjudicator)','A'),
(55,'Adjudication Assistant','A'),
(56,'Process Server','A'),
(57,'Driver','A'),
(58,'Computer Programmer I (Support Staff)','A'),
(59,'Computer Maintenance Technologist I (Support Staff)','A'),
(60,'Support Staff','A'),
(61,'Utility/Liaison Worker','A'),
(62,'Media Production Specialist I (Support Staff)','A'),
(63,'Creative Arts Specialist','A'),
(64,'Media Production Assistant I (Support Staff)','A'),
(65,'Creative Arts Specialist I (Support Staff)','A'),
(66,'Electrician','A'),
(67,'Carpenter','A'),
(68,'Decongestion Officer ','A'),
(69,'Records Officer ','A'),
(70,'Stenographer','A'),
(71,'Technical Adviser','A')
;